components/Login/Login.tsx

Back btn to return to `/` and the same link on logo

feat: back btn on login page

---

app/(public)/article/[slug]/page.tsx
app/(public)/components/ArticleContent.tsx
app/(public)/components/Articles.tsx
app/(public)/components/Footer.tsx
app/(public)/components/LandingPageContent.tsx
app/(public)/page.tsx
lib/api/article.ts
middleware.ts
next.config.mjs

feat: cx articles

---

.github/workflows/main.yml
app/(public)/components/Header.tsx
components/RequestDetails/RequestCard.tsx
jest.config.ts
lib/firebase/__tests__/logs.test.ts
lib/firebase/logs.ts
lib/tests/jest.setup.ts
lib/tests/mocks/router.ts
package.json
tsconfig.json
yarn.lock

detectChanges fails if some values are `null`, fix that
- add tests

fix: detecting changes

---

app/(public)/components/Header.tsx
components/Profile/Profile.tsx

Feat: public page use Profile

---

app/(public)/components/ContactForm.tsx
app/api/contact/route.ts
components/Layout/Layout.tsx
components/RequestsList/RequestsList.tsx
components/ResolvedList/ResolvedList.tsx
components/Settings/SaveOfferTab/DynamicSaveOfferSection.tsx
components/Settings/SaveOfferTab/SaveOfferCard.tsx
components/Settings/SaveOfferTab/SaveOfferTab.tsx
components/Settings/Settings.tsx
components/UploadCSV/FileUpload.tsx
components/UploadCSV/UploadCSV.tsx
lib/db/schema.ts
lib/email/templates/ContactFormTemplate.ts
lib/email/templates/DynamicSaveOfferTemplate.ts
lib/email/templates/index.ts

This PR introduces a new feature allowing tenants to request dynamic save offers. This setting enables automatic generation of tailored offers for customers based on their behavior and cancellation requests.
- Added a new section in the SaveOffersTab for Dynamic Save Offers
- Implemented a mutation to update tenant data with dynamic offer request status
- Updated Tenant schema to include new fields for dynamic offer requests
- Created `DynamicSaveOfferSection` component in `SaveOffersTab`
- Utilized existing `updateTenant` function for API communication
- Added new fields to Tenant schema: `saveOffersDynamicRequestSent` and `saveOffersDynamicRequestSentAt`
- Manually tested the new UI component and API interaction
- Verified that tenant data updates correctly upon request submission
- …

Dynamic save offer

---

components/Settings/Settings.tsx

feat: no proxy fee tab for providers

---

app/api/change-password/route.ts
components/Login/SignUpForm.tsx
components/Settings/MyAccountTab/ChangePasswordForm.tsx
components/Settings/MyAccountTab/MyAccountTab.tsx
components/Settings/Settings.tsx
utils/passwordValidation.ts

feat: change password

---

components/UploadCSV/FileUpload.tsx
components/UploadCSV/SelectProvider.tsx

fix: select providers on upload page

---

app/layout.tsx

- Added HubSpot tracking script to root layout for site-wide analytics
- Ensures proper protocol (https://) for script source
- Script loads asynchronously to prevent blocking page render

Feature: HubSpot integration

---

constants/authFields.json

Add shipping address to authenticating fields

Feature: shipping address

---

README.md
app/api/request/route.ts

Set maximum duration of a serverless function for 5 min

feat: increase maxDuration for request api

---

components/Settings/AuthenticationFieldsTab.tsx
constants/authFields.json

Refactor: Authentication fields

---

app/(public)/components/landing-page/ApiForProxies.tsx

Fix for the bug about Get Started button not having a link

fix: link on the button

---

app/(public)/schedule-demo/page.tsx
app/api/login/route.ts
components/Overview/AvgResponseTimeChart.tsx
components/Overview/SourcesCard.tsx

**Title:** UI Enhancements and No Data Handling
**Summary:**
- **UI Consistency:**
-  Fixed `AvgResponseTimeChart` and `SourcesCard` for consistent appearance.
- **No Data Handling:**
- Display "No data available" message when no data is present.
**Additional:**
- Minor changes to the "Schedule Demo" page as per the attached image.
login as `sorokinvj+no_req@gmail.com` with password `Q1w2e3r4t5y^`

Fix: minor bugs

---

app/layout.tsx
package.json
yarn.lock

- Google Analytics
- Vercel Analytics

feat: add analytics

---

app/(public)/apply/page.tsx
app/(public)/components/apply/ApplyLandingPage.tsx
app/(public)/components/apply/WaitlistForm.tsx
app/(public)/components/landing-page/Hero.tsx
app/(public)/layout.tsx
app/(public)/page.tsx
components/Settings/AuthenticationFieldsTab.tsx
constants/authFields.json
lib/email/templates/RegisterFormTemplate.ts
middleware.ts

- change to main page heading and subheading copies
- /register > /apply with all the changes to the copies
- changes to auth fields setting page
- add phone number to /apply form and email notification

Updates to /apply page

---

app/(public)/components/Articles.tsx
app/(public)/terms-of-service/page.tsx
app/api/invitations/[id]/route.ts
app/api/users/exists/route.ts
components/OrgOnboardingWizard/OrgOnboardingWizard.tsx
components/Settings/InviteNewUserModal.tsx
components/Settings/MyTeamTab.tsx
constants/app.contants.ts
hooks/useEmailValidation.ts
lib/api/user.ts

- New onboarding popup
- Improved email validation to prevent adding users that already registered in the database
- Added ability to delete invitations from MyTeamTab

New onboarding popup

---

lib/email/templates/application-received.html

fix: email text

---

app/(public)/apply/page.tsx
app/(public)/components/landing-page/Hero.tsx

fix: copy and meta

---

components/Login/ResetPasswordForm.tsx
components/Login/SignUpForm.tsx
components/Login/SuccessMessage.tsx

1. Created a reusable `SuccessMessage` component that handles automatic login after successful user actions
2. Implemented progressive status updates to improve user experience
3. Added fallback login button for error scenarios
- Added status tracking (`success`, `signing-in`, `complete`, `error`) for better UX
- Implemented automatic login flow using Firebase authentication
- Added visual feedback with different icons and message colors based on status
- Integrated session creation via `/api/login` endpoint
Please verify:
- Password is only used for immediate login and not stored
- Session creation follows the same secure flow as regular login
- Error messages don't expose sensitive information
- Progressive status messages keep users informed
- Color-coded messages for different states …

Feature: Auto login
